info:
    version: ""
    title: data_source_huaweicloud_ccm_private_ca_config_console
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: CCM
paths:
    /v1/pca/config/console:
        GET:
            tag: CCM
