info:
    version: ""
    title: data_source_huaweicloud_hss_baseline_all_risk_config_check_rules
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: HSS
paths:
    /v5/{project_id}/baseline/risk-config/check-rules:
        GET:
            tag: HSS
